config/routes.rb
XeroUploader2::Application.routes.draw do
  resources :transactions do
    collection {get 'delete_all'}
  end
  resources :transaction_imports
  resources :funds
  resources :xero do
    collection {get 'send_to'}
  end
  

  root 'transactions#index'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.includes(:fund).load
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions/import
  def import
    Product.import(import_params)
    redirect_to transactions_path, notice: "Transactions imported."

  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render action: 'show', status: :created, location: @transaction }
      else
        format.html { render action: 'new' }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end

  # DELETE /transactions/delete_all
  # DELETE /transactions/delete_all.json
  def delete_all
    @transaction = Transaction.all
    @transaction.each {|t| t.destroy}
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Everything was deleted.'  }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:fund_id, :xero_type, :name, :date, :due_date, :description, :quantity, :unit_amount, :account_code, :currency_code, :currency_rate, :reference, :invoice_number)
    end

    def import_params
      params.require(:file)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fund %><br>
    <%= f.text_field :fund %>
  </div>
  <div class="field">
    <%= f.label :xero_type %><br>
    <%= f.text_field :xero_type %>
  </div>
  <div class="field">
    <%= f.label :invoice_number %><br>
    <%= f.text_field :invoice_number %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.datetime_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :unit_amount %><br>
    <%= f.text_field :unit_amount %>
  </div>
  <div class="field">
    <%= f.label :account_code %><br>
    <%= f.text_field :account_code %>
  </div>
  <div class="field">
    <%= f.label :currency_code %><br>
    <%= f.text_field :currency_code %>
  </div>
  <div class="field">
    <%= f.label :currency_rate %><br>
    <%= f.text_field :currency_rate %>
  </div>
  <div class="field">
    <%= f.label :xero_invoice_id%><br>
    <%= f.text_field :xero_invoice_id %>
  </div>
  <div class="field">
    <%= f.label :reference %><br>
    <%= f.text_field :reference %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<h2>Import Transactions</h2>
<p><%= link_to "Import Transactions", new_transaction_import_path %></p>

<p><%= link_to 'New Transaction', new_transaction_path %> |
<%= link_to 'Send All to Xero', send_to_xero_index_path %> |
<%= link_to 'Destroy ALL!', delete_all_transactions_path, data: { confirm: 'Are you sure?' }   %></p>

<table>
  <thead>
    <tr>
      <th>Fund</th>
      <th>Invoice Number</th>
      <th>Type</th>
      <th>Name</th>
      <th>Date</th>
      <th>Due Date</th>
      <th>Description</th>
      <th>Quantity</th>
      <th>Unit amount</th>
      <th>Account Code</th>
      <th>Currency code</th>
      <th>Currency rate</th>
      <th>Xero Invoice ID</th>
      <th>Reference</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.fund.name %></td>
        <td><%= transaction.invoice_number %></td>
        <td><%= transaction.xero_type %></td>
        <td><%= transaction.name %></td>
        <td><%= transaction.date %></td>
        <td><%= transaction.due_date %></td>
        <td><%= transaction.description %></td>
        <td><%= transaction.quantity %></td>
        <td><%= transaction.unit_amount %></td>
        <td><%= transaction.account_code %></td>
        <td><%= transaction.currency_code %></td>
        <td><%= transaction.currency_rate %></td>
        <td><%= transaction.xero_invoice_id %></td>
        <td><%= transaction.reference %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>
<%= link_to 'Send All to Xero', send_to_xero_index_path %>
<%= link_to 'Destroy ALL!', delete_all_transactions_path, data: { confirm: 'Are you sure?' }   %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fund:</strong>
  <%= @transaction.fund %>
</p>

<p>
  <strong>Invoice Number:</strong>
  <%= @transaction.invoice_number %>
</p>

<p>
  <strong>Type:</strong>
  <%= @transaction.xero_type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @transaction.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @transaction.date %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @transaction.due_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @transaction.description %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @transaction.quantity %>
</p>

<p>
  <strong>Unit amount:</strong>
  <%= @transaction.unit_amount %>
</p>

<p>
  <strong>Account code:</strong>
  <%= @transaction.account_code %>
</p>

<p>
  <strong>Currency code:</strong>
  <%= @transaction.currency_code %>
</p>

<p>
  <strong>Currency rate:</strong>
  <%= @transaction.currency_rate %>
</p>

<p>
  <strong>Xero Invoice ID:</strong>
  <%= @transaction.xero_invoice_id %>
</p>

<p>
  <strong>Reference:</strong>
  <%= @transaction.reference %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>