config/routes.rb
XeroUploader2::Application.routes.draw do
  resources :transactions do
    collection {get 'delete_all'}
  end
  resources :transaction_imports
  resources :funds
  resources :xero do
    collection {get 'send_to'}
  end
  

  root 'transactions#index'

end

app/models/fund.rb
class Fund < ActiveRecord::Base
  has_many :transactions

  def connect_to_xero
    @xero = Xero.new(self.xero_key,self.xero_secret)
  end

  def xero
    @xero || self.connect_to_xero
  end


end

app/controllers/funds_controller.rb
class FundsController < ApplicationController
  before_action :set_fund, only: [:show, :edit, :update, :destroy]

  # GET /funds
  # GET /funds.json
  def index
    @funds = Fund.all
  end

  # GET /funds/1
  # GET /funds/1.json
  def show
  end

  # GET /funds/new
  def new
    @fund = Fund.new
  end

  # GET /funds/1/edit
  def edit
  end

  # POST /funds
  # POST /funds.json
  def create
    @fund = Fund.new(fund_params)

    respond_to do |format|
      if @fund.save
        format.html { redirect_to @fund, notice: 'Fund was successfully created.' }
        format.json { render action: 'show', status: :created, location: @fund }
      else
        format.html { render action: 'new' }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funds/1
  # PATCH/PUT /funds/1.json
  def update
    respond_to do |format|
      if @fund.update(fund_params)
        format.html { redirect_to @fund, notice: 'Fund was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funds/1
  # DELETE /funds/1.json
  def destroy
    @fund.destroy
    respond_to do |format|
      format.html { redirect_to funds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fund
      @fund = Fund.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fund_params
      params.require(:fund).permit(:name, :code, :xero_key, :xero_secret)
    end
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/views/funds/_form.html.erb
<%= form_for(@fund) do |f| %>
  <% if @fund.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fund.errors.count, "error") %> prohibited this fund from being saved:</h2>

      <ul>
      <% @fund.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :xero_key %><br>
    <%= f.text_field :xero_key %>
  </div>
  <div class="field">
    <%= f.label :xero_secret %><br>
    <%= f.text_field :xero_secret %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/funds/edit.html.erb
<h1>Editing fund</h1>

<%= render 'form' %>

<%= link_to 'Show', @fund %> |
<%= link_to 'Back', funds_path %>

app/views/funds/index.html.erb
<h1>Listing funds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Xero key</th>
      <th>Xero secret</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @funds.each do |fund| %>
      <tr>
        <td><%= fund.name %></td>
        <td><%= fund.code %></td>
        <td><%= fund.xero_key %></td>
        <td><%= fund.xero_secret %></td>
        <td><%= link_to 'Show', fund %></td>
        <td><%= link_to 'Edit', edit_fund_path(fund) %></td>
        <td><%= link_to 'Destroy', fund, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fund', new_fund_path %>

app/views/funds/new.html.erb
<h1>New fund</h1>

<%= render 'form' %>

<%= link_to 'Back', funds_path %>

app/views/funds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fund.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @fund.code %>
</p>

<p>
  <strong>Xero key:</strong>
  <%= @fund.xero_key %>
</p>

<p>
  <strong>Xero secret:</strong>
  <%= @fund.xero_secret %>
</p>

<%= link_to 'Edit', edit_fund_path(@fund) %> |
<%= link_to 'Back', funds_path %>